<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('posts')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Map category and province names to their IDs
        $categoryMap = DB::table('categories')->pluck('id', 'name')->mapWithKeys(function($id, $name) {
            return [strtolower($name) => $id];
        });
        $provinceMap = DB::table('provinces')->pluck('id', 'name_en')->mapWithKeys(function($id, $name) {
            return [strtolower($name) => $id];
        });

        $posts = [
            [
                'title' => 'Angkor Wat',
                'province' => 'Siem Reap',
                'category' =>  'Temple',
                'content' => "Angkor Wat, the crown jewel of Cambodia, stands as the world's largest religious monument and a breathtaking testament to the genius of the Khmer Empire. Built in the 12th century by King Suryavarman II, this vast temple complex was originally dedicated to the Hindu god Vishnu before gradually transforming into a Buddhist center. Its perfect symmetry, intricate bas-reliefs depicting Hindu epics, and the iconic five towers that silhouette against the sunrise make it a site of profound spiritual and architectural significance. Surrounded by a massive moat, Angkor Wat is a microcosm of the Hindu universe, leaving visitors in awe of its scale and artistry.",
                'image' => 'posts/AngkorWat.jpg',
                'published_at' => Carbon::now()->subDays(10),
                'created_at' => Carbon::now()->subDays(20),
                'updated_at' => Carbon::now()->subDays(20),
            ],
            [
                'title' => 'Bayon Temple',
                'province' => 'Siem Reap',
                'category' =>  'Temple',
                'content' => "Located at the heart of the ancient city of Angkor Thom, the Bayon Temple is a masterpiece of Khmer art, famous for its enigmatic stone faces. Over 200 serene and smiling faces, thought to be a depiction of King Jayavarman VII himself as a bodhisattva, gaze out from its 54 Gothic-style towers. Unlike the classical simplicity of Angkor Wat, Bayon is a complex and richly decorated temple. Its lower galleries contain stunning bas-reliefs that vividly portray not only historical battles but also scenes of everyday life in 12th-century Cambodia, offering a unique window into the past.",
                'image' => 'posts/Bayon_Temple.jpg',
                'published_at' => Carbon::now()->subDays(9),
                'created_at' => Carbon::now()->subDays(19),
                'updated_at' => Carbon::now()->subDays(19),
            ],
            [
                'title' => 'Ta Prohm',
                'province' => 'Siem Reap',
                'category' =>  'Temple',
                'content' => "Famed for its appearance in the movie 'Tomb Raider,' Ta Prohm is the quintessential 'lost temple.' Left largely to the mercy of the jungle, its stone walls are locked in the powerful embrace of giant silk-cotton and strangler fig trees. The roots snake over doorways and through crumbling galleries, creating an otherworldly atmosphere where nature and architecture merge. Originally a Buddhist monastery and university founded by King Jayavarman VII, Ta Prohm was intentionally left unrestored to showcase how these ancient structures appeared when they were rediscovered, offering a hauntingly beautiful and romantic experience.",
                'image' => 'posts/Ta_Prohm.webp',
                'published_at' => Carbon::now()->subDays(8),
                'created_at' => Carbon::now()->subDays(18),
                'updated_at' => Carbon::now()->subDays(18),
            ],
            [
                'title' => 'Bokor Mountain',
                'province' => 'Kampot',
                'category' =>  'Mountain',
                'content' => "Rising over 1,000 meters above the Cambodian coastline, Phnom Bokor National Park offers a cool, misty escape. The main attraction is the abandoned French colonial hill station, a ghost town featuring the hauntingly beautiful Bokor Palace Hotel & Casino and a weathered Catholic church. These ruins, often shrouded in fog, offer a glimpse into a bygone era. Today, new developments coexist with the old, but the park remains a sanctuary of lush jungle, rare wildlife, and spectacular viewpoints that stretch across the Gulf of Thailand on a clear day, making the winding journey to the top well worth the effort.",
                'image' => 'posts/Bokor_Mountain.jpg',
                'published_at' => Carbon::now()->subDays(7),
                'created_at' => Carbon::now()->subDays(17),
                'updated_at' => Carbon::now()->subDays(17),
            ],
            [
                'title' => 'Koh Rong',
                'province' => 'Preah Sihanouk',
                'category' =>  'Island',
                'content' => "Koh Rong is Cambodia's second-largest island, a tropical paradise that perfectly blends vibrant beach life with untouched nature. It boasts over 23 pristine white-sand beaches, each with its own character. The main tourist hub, Koh Touch, is famous for its bustling nightlife and guesthouses. For a more secluded experience, travelers can venture to Long Beach for spectacular sunsets or snorkel in the crystal-clear turquoise waters of Lonely Beach. A magical highlight is swimming at night among bioluminescent plankton, which light up the water around you like stars.",
                'image' => 'posts/Koh_Rong.jpg',
                'published_at' => Carbon::now()->subDays(6),
                'created_at' => Carbon::now()->subDays(16),
                'updated_at' => Carbon::now()->subDays(16),
            ],
            [
                'title' => 'Koh Rong Samloem',
                'province' => 'Preah Sihanouk',
                'category' =>  'Island',
                'content' => "A short ferry ride from its more boisterous sister island, Koh Rong Samloem offers a more serene and peaceful escape. This island is the epitome of a tranquil paradise, with the stunning, crescent-shaped Saracen Bay at its heart. Here, you'll find idyllic resorts, overwater swings, and calm, shallow waters perfect for relaxation. The island is less developed, making it ideal for nature lovers who can enjoy snorkeling at Lazy Beach or trekking through the lush jungle interior to discover hidden coves and waterfalls. It's the perfect place to disconnect and embrace the slow pace of island life.",
                'image' => 'posts/Koh_Rong_Samloem.jpg',
                'published_at' => Carbon::now()->subDays(5),
                'created_at' => Carbon::now()->subDays(15),
                'updated_at' => Carbon::now()->subDays(15),
            ],
            [
                'title' => 'Kirirom National Park',
                'province' => 'Kampong Speu',
                'category' =>  'Nationalpark',
                'content' => "Meaning 'Mountain of Joy,' Kirirom National Park is a unique high-altitude plateau known for its beautiful pine forests, a rare sight in Cambodia. Its cooler climate provides a refreshing retreat from the heat of the plains and nearby Phnom Penh. The park is a haven for nature lovers, offering hiking trails that wind through the fragrant pine trees, past cascading waterfalls and local farms. It’s an ideal destination for camping, picnicking, and discovering the diverse flora and fauna that thrive in this highland ecosystem.",
                'image' => 'posts/Kirirom_National_Park.jpg',
                'published_at' => Carbon::now()->subDays(4),
                'created_at' => Carbon::now()->subDays(14),
                'updated_at' => Carbon::now()->subDays(14),
            ],
            [
                'title' => 'Phnom Kulen',
                'province' => 'Siem Reap',
                'category' =>  'Mountain',
                'content' => "Phnom Kulen is considered by Cambodians to be the most sacred mountain in the country. It was here in 802 AD that King Jayavarman II declared himself a 'devaraja' (god-king), marking the birth of the great Khmer Empire. Today, it remains a major pilgrimage site. Visitors can explore the River of a Thousand Lingas, where ancient phallic symbols are carved into the riverbed to bless the water flowing to the Angkorian plains. The mountain is also home to a large reclining Buddha statue and two beautiful waterfalls that are popular spots for swimming and picnicking.",
                'image' => 'posts/Phnom_Kulen.jpg',
                'published_at' => Carbon::now()->subDays(3),
                'created_at' => Carbon::now()->subDays(13),
                'updated_at' => Carbon::now()->subDays(13),
            ],
            [
                'title' => 'Preah Vihear Temple',
                'province' => 'Preah Vihear',
                'category' =>  'Temple',
                'content' => "Perched dramatically atop a 525-meter cliff in the Dângrêk Mountains, Preah Vihear Temple is a UNESCO World Heritage site with an unparalleled setting. This ancient Hindu temple, built over several centuries, was dedicated to the god Shiva. Its series of sanctuaries, linked by a system of causeways and staircases over an 800-meter axis, is a masterpiece of Khmer architecture. The real highlight is the breathtaking panoramic view from the top, which extends for miles across the vast Cambodian plains, offering a sense of awe and wonder.",
                'image' => 'posts/Preah_Vihear_Temple.jpg',
                'published_at' => Carbon::now()->subDays(2),
                'created_at' => Carbon::now()->subDays(12),
                'updated_at' => Carbon::now()->subDays(12),
            ],
            [
                'title' => 'Wat Phnom',
                'province' => 'Phnom Penh',
                'category' =>  'Temple',
                'content' => "Wat Phnom is the historical and spiritual heart of Cambodia's capital city. According to legend, the first pagoda was erected here in 1372 by a wealthy widow named Penh after she discovered four sacred Buddha statues in a floating Koki tree. The temple sits on a 27-meter-high man-made hill, the only one in the city. Today, it's a bustling hub of activity where locals come to pray for good fortune and success. The complex, with its central stupa, shrines, and lush gardens, offers a peaceful green space and a glimpse into the city's founding myth.",
                'image' => 'posts/Wat_Phnom.jpg',
                'published_at' => Carbon::now()->subDay(),
                'created_at' => Carbon::now()->subDays(11),
                'updated_at' => Carbon::now()->subDays(11),
            ],
            [
                'title' => 'Royal Palace',
                'province' => 'Phnom Penh',
                'category' => 'Palace' ,
                'content' => 'A grand complex serving as the official residence of Cambodia’s royal family.',
                'image' => 'posts/RoyalPalace.jpg',
                'published_at' => Carbon::now()->subDays(10),
                'created_at' => Carbon::now()->subDays(10),
                'updated_at' => Carbon::now()->subDays(10),
            ],
            [
                'title' => 'Independence Monument',
                'province' => 'Phnom Penh',
                'category' =>  'Monument',
                'content' => 'A landmark monument honoring Cambodia’s independence from France in 1953.',
                'image' => 'posts/Independence_Monument.png',
                'published_at' => Carbon::now()->subDays(9),
                'created_at' => Carbon::now()->subDays(9),
                'updated_at' => Carbon::now()->subDays(9),
            ],
            [
                'title' => 'Tonle Sap Lake',
                'province' => 'Siem Reap',
                'category' =>  'Lake',
                'content' => 'Southeast Asia\'s largest freshwater lake, home to floating villages and diverse wildlife.',
                'image' => 'posts/Tonle_Sap_Lake.jpg',
                'published_at' => Carbon::now()->subDays(8),
                'created_at' => Carbon::now()->subDays(8),
                'updated_at' => Carbon::now()->subDays(8),
            ],
            [
                'title' => 'Cardamom Mountains',
                'province' => 'Koh Kong',
                'category' =>  'Mountain',
                'content' => 'A vast, untouched rainforest region perfect for eco-tourism, trekking, and wildlife exploration.',
                'image' => 'posts/Cardamom_Mountains.webp',
                'published_at' => Carbon::now()->subDays(7),
                'created_at' => Carbon::now()->subDays(7),
                'updated_at' => Carbon::now()->subDays(7),
            ],
            [
                'title' => 'Sambor Prei Kuk',
                'province' => 'Kampong Thom',
                'category' =>  'Temple',
                'content' => 'A pre-Angkorian archaeological site with ancient temples hidden in the jungle.',
                'image' => 'posts/Sambor_Prei_Kuk.jpg',
                'published_at' => Carbon::now()->subDays(6),
                'created_at' => Carbon::now()->subDays(6),
                'updated_at' => Carbon::now()->subDays(6),
            ],
            [
                'title' => 'Otres Beach',
                'province' => 'Preah Sihanouk',
                'category' =>  'Beach',
                'content' => 'A peaceful stretch of sandy beach, popular with backpackers and nature lovers.',
                'image' => 'posts/Otres_Beach.jpg',
                'published_at' => Carbon::now()->subDays(5),
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => Carbon::now()->subDays(5),
            ],
            [
                'title' => 'Kampot River',
                'province' => 'Kampot',
                'category' =>  'River',
                'content' => 'A scenic river perfect for kayaking, sunset cruises, and riverside dining.',
                'image' => 'posts/Kampot_River.jpg',
                'published_at' => Carbon::now()->subDays(4),
                'created_at' => Carbon::now()->subDays(4),
                'updated_at' => Carbon::now()->subDays(4),
            ],
            [
                'title' => 'Phnom Sampov',
                'province' => 'Battambang',
                'category' =>  'Mountain',
                'content' => 'A hilltop temple complex with war memorials and the famous bat cave.',
                'image' => 'posts/Phnom_Sampov.jpg',
                'published_at' => Carbon::now()->subDays(3),
                'created_at' => Carbon::now()->subDays(3),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'title' => 'Ek Phnom Temple',
                'province' => 'Battambang',
                'category' => 'Temple',
                'content' => 'A partially collapsed 11th-century temple surrounded by rural countryside.',
                'image' => 'posts/Ek_Phnom_Temple.jpg',
                'published_at' => Carbon::now()->subDays(2),
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'title' => 'Ream National Park',
                'province' => 'Preah Sihanouk',
                'category' => 'Nationalpark',
                'content' => 'A coastal park featuring mangroves, islands, wildlife, and quiet beaches.',
                'image' => 'posts/Ream_National_Park.jpg',
                'published_at' => Carbon::now()->subDay(),
                'created_at' => Carbon::now()->subDay(),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'title' => 'Raffles Hotel Le Royal',
                'province' => 'Phnom Penh',
                'category' => 'Hotel',
                'content' => 'An iconic heritage hotel, Raffles Le Royal offers a journey back to a bygone era of elegance and charm. With its classic French colonial architecture, lush tropical gardens, and two swimming pools, it provides a sanctuary in the heart of the capital. Don’t miss a signature cocktail at the legendary Elephant Bar. From the hotel, you can easily explore the city’s key attractions. A short trip takes you to the historic Wat Phnom, the dazzling Royal Palace, the Silver Pagoda, and the National Museum, which houses priceless Khmer artifacts. A stroll along the nearby riverside promenade is perfect for a relaxing evening.',
                'image' => 'posts/RafflesHotelLeRoyal.webp',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Rosewood Phnom Penh',
                'province' => 'Phnom Penh',
                'category' => 'Hotel',
                'content' => 'Occupying the top 14 floors of the modern Vattanac Capital Tower, Rosewood offers unparalleled luxury and breathtaking 360-degree views of Phnom Penh. The hotel features ultra-modern rooms, a serene spa, and exquisite dining options, including the stunning Sora Sky Bar. Staying here places you in a prime location to explore. You can visit the art deco Central Market (Phsar Thmey) for shopping, discover the nearby historic Phnom Penh Railway Station, or take a short tuk-tuk ride to the bustling Riverside area for dining and sightseeing.',
                'image' => 'posts/RosewoodPhnomPenh.jpg',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Park Hyatt Siem Reap',
                'province' => 'Siem Reap',
                'category' => 'Hotel',
                'content' => 'A luxurious blend of Khmer-inspired design and modern comfort, the Park Hyatt is a sophisticated oasis in the heart of Siem Reap. This elegant hotel is known for its beautiful courtyard, two swimming pools, and art deco aesthetics. It offers a tranquil retreat just steps away from the city’s vibrant center. When you venture out, the lively Pub Street and the bustling Old Market (Phsar Chas) are within easy walking distance. The magnificent temples of the Angkor Archaeological Park, including the world-famous Angkor Wat, are just a short drive away.',
                'image' => 'posts/ParkHyattSiemReap.jpg',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Song Saa Private Island',
                'province' => 'Preah Sihanouk',
                'category' => 'Hotel',
                'content' => 'Song Saa offers the ultimate "barefoot luxury" experience on its own private island in the Koh Rong archipelago. The resort features stunning overwater, jungle, and ocean-view villas, each with a private pool. It is a leader in sustainable tourism, with a focus on protecting the local marine life and supporting the nearby community. While the island itself is the main destination, activities abound. You can explore the resort’s private marine reserve by snorkeling or kayaking, relax at the world-class spa, or take a boat to the nearby village of Prek Svay to experience local life.',
                'image' => 'posts/SongSaaPrivateIsland.jpg',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Knai Bang Chatt',
                'province' => 'Kep',
                'category' => 'Hotel',
                'content' => 'Located in the charming coastal town of Kep, Knai Bang Chatt is a unique boutique resort composed of beautifully restored 1960s modernist villas. The hotel exudes an atmosphere of serene tranquility, with a stunning infinity pool that looks out over the Gulf of Thailand. From this peaceful base, you can easily explore the best of Kep. A must-do is visiting the famous Kep Crab Market for fresh seafood. For nature lovers, Kep National Park offers scenic hiking trails with monkeys and beautiful viewpoints. You can also take a short boat trip to the rustic Rabbit Island (Koh Tonsay) for a day of swimming and relaxation.',
                'image' => 'posts/Knai BangChatt.jpg',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Amber Kampot',
                'province' => 'Kampot',
                'category' => 'Hotel',
                'content' => 'Amber Kampot is a premier luxury resort situated on the tranquil banks of the Kampot River. It features contemporary and spacious villas, many with their own private pools, set against a backdrop of lush greenery. The resort is a perfect blend of modern comfort and natural beauty. Staying here allows you to enjoy the peaceful riverside while being close to local attractions. You can take a sunset cruise on the river to see the fireflies, visit the famous local pepper plantations to learn about world-renowned Kampot pepper, or take a day trip up the winding road to explore the cool climate and historic ruins of Bokor National Park.',
                'image' => 'posts/AmberKampot.jpg',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Jaya House River Park',
                'province' => 'Siem Reap',
                'category' => 'Hotel',
                'content' => 'A tranquil gem located along the Siem Reap River, Jaya House is a boutique hotel with a strong commitment to environmental sustainability and community. The hotel is renowned for its exceptional service, lush tropical gardens, and two stunning swimming pools. Its location offers a peaceful escape from the downtown hustle. From here, you can enjoy a scenic drive along the river to the Angkor complex. It is also well-positioned for visiting the Landmine Museum and the beautiful temple of Banteay Srei. The hotel offers free tuk-tuk service to the city center for when you wish to explore Pub Street and the markets.',
                'image' => 'posts/JayaHouseRiverPark.jpg',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Six Senses Krabey Island',
                'province' => 'Preah Sihanouk',
                'category' => 'Hotel',
                'content' => 'Six Senses Krabey Island is a secluded paradise dedicated to wellness, luxury, and nature. The resort features 40 private pool villas nestled into the lush vegetation of a pristine private island. The world-class spa is a highlight, offering a wide range of holistic treatments and wellness programs. The island itself is the main attraction, with a private beach, water sports, and beautiful nature trails. From the mainland jetty, you are close enough to explore the mangrove forests of Ream National Park before or after your island escape, giving you a perfect combination of jungle and sea.',
                'image' => 'posts/SixSensesKrabeyIsland.jpg',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Shinta Mani Angkor',
                'province' => 'Siem Reap',
                'category' => 'Hotel',
                'content' => 'Designed by the acclaimed architect Bill Bensley, Shinta Mani Angkor is a stylish boutique hotel that artfully blends modern design with Khmer inspiration. Located in the quiet French Quarter, the hotel is also a leader in responsible tourism, with proceeds supporting the Shinta Mani Foundation to empower the local community. It offers a sophisticated and peaceful stay. From the hotel, you are just a short walk from the Angkor National Museum and the vibrant restaurant scene. The main temples of Angkor Wat are easily accessible by a short tuk-tuk ride, making it an ideal base for both cultural exploration and relaxation.',
                'image' => 'posts/ShintaManiAngkor.jpg',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
            [
                'title' => 'Mayura Hill Resort',
                'province' => 'Mondulkiri',
                'category' => 'Hotel',
                'content' => 'Escape to the cool, rolling hills of Cambodia’s eastern province at Mayura Hill Resort. This boutique resort offers comfortable and elegant villas with stunning panoramic views of the surrounding landscape, providing a luxurious base for exploring this unique region. Mondulkiri is known for its natural beauty and indigenous culture. From the resort, you can arrange a visit to the acclaimed Elephant Valley Project, an ethical elephant sanctuary. You can also travel to the thunderous Bou Sra Waterfall, one of Cambodia’s largest, or visit local Bunong villages to learn about their unique culture and coffee plantations.',
                'image' => 'posts/MayuraHillResort.avif',
                'published_at' => Carbon::now()->subDays(1),
                'created_at' => Carbon::now()->subDays(1),
                'updated_at' => Carbon::now()->subDays(1),
            ],
             // -- Mountains --
     
    [
        'title' => 'Phnom Aural',
        'province' => 'Kampong Speu',
        'category' =>  'Mountain',
        'content' => "As Cambodia's tallest peak, standing at 1,813 meters, Phnom Aural offers the ultimate trekking challenge in the country. Located within a wildlife sanctuary in the Cardamom Mountains, the multi-day hike takes adventurers through dense jungle, bamboo forests, and past diverse wildlife, rewarding them with unparalleled views from the summit.",
        'image' => 'posts/phnom_aural.jpg',
        'published_at' => Carbon::now()->subDays(3),
        'created_at' => Carbon::now()->subDays(3),
        'updated_at' => Carbon::now()->subDays(3),
    ],
    [
        'title' => 'Phnom Chhnork',
        'province' => 'Kampot',
        'category' =>  'Mountain',
        'content' => "Phnom Chhnork is a small mountain hill known for its remarkable limestone cave temple. A 203-step staircase leads to the cave entrance, which houses a 7th-century Funan-era brick temple dedicated to Shiva. The natural cave formations and the ancient sanctuary within create a unique and spiritual atmosphere.",
        'image' => 'posts/phnom_chhnork.jpg',
        'published_at' => Carbon::now()->subDays(3),
        'created_at' => Carbon::now()->subDays(3),
        'updated_at' => Carbon::now()->subDays(3),
    ],

    // -- Beaches --
    [
        'title' => 'Sok San Beach',
        'province' => 'Preah Sihanouk',
        'category' =>  'Beach',
        'content' => "Also known as Long Beach on Koh Rong, Sok San Beach is a 7km stretch of pristine, powdery white sand and turquoise water. Its remote location offers a tranquil paradise, perfect for swimming, sunbathing, and watching spectacular sunsets. The area has a mix of luxury resorts and simple bungalows.",
        'image' => 'posts/sok_san_beach.jpg',
        'published_at' => Carbon::now()->subDays(6),
        'created_at' => Carbon::now()->subDays(6),
        'updated_at' => Carbon::now()->subDays(6),
    ],
    [
        'title' => 'Lazy Beach',
        'province' => 'Preah Sihanouk',
        'category' =>  'Beach',
        'content' => "Tucked away on the western side of Koh Rong Samloem, Lazy Beach is a golden-sand cove that lives up to its name. Reachable by a jungle walk or boat, this secluded spot is perfect for unwinding. With just one resort, it offers a peaceful escape with excellent snorkeling and stunning sunset views.",
        'image' => 'posts/lazy_beach.webp',
        'published_at' => Carbon::now()->subDays(6),
        'created_at' => Carbon::now()->subDays(6),
        'updated_at' => Carbon::now()->subDays(6),
    ],
    [
        'title' => 'Kep Beach',
        'province' => 'Kep',
        'category' =>  'Beach',
        'content' => "Once a rather narrow shore, Kep Beach has been transformed with imported white sand, creating a pleasant and popular spot for families. The calm waters are ideal for swimming, and the beachfront is lined with vendors selling fresh seafood and renting out chairs, making for a perfect, relaxed seaside day.",
        'image' => 'posts/kep_beach.webp',
        'published_at' => Carbon::now()->subDays(6),
        'created_at' => Carbon::now()->subDays(6),
        'updated_at' => Carbon::now()->subDays(6),
    ],

    // -- Islands --
     
    [
        'title' => 'Koh Totang',
        'province' => 'Koh Kong',
        'category' =>  'Island',
        'content' => "Part of the Koh S'Dach archipelago, Koh Totang is an off-grid, eco-friendly paradise. With no wifi and limited electricity, it's the ultimate escape. Home to just one small guesthouse, the island is surrounded by vibrant coral reefs, making it a perfect destination for snorkeling, diving, and digital detoxing.",
        'image' => 'posts/koh_totang.jpg',
        'published_at' => Carbon::now()->subDays(9),
        'created_at' => Carbon::now()->subDays(9),
        'updated_at' => Carbon::now()->subDays(9),
    ],
    [
        'title' => 'Rabbit Island (Koh Tonsay)',
        'province' => 'Kep',
        'category' =>  'Island',
        'content' => "A short boat ride from Kep, Rabbit Island offers a rustic and charming getaway. Known for its golden sand beach, simple seaside bungalows, and laid-back vibe, it's a place to disconnect. Enjoy fresh seafood cooked by local families, swim in the warm, shallow waters, or simply relax in a hammock.",
        'image' => 'posts/rabbit_island.jpg',
        'published_at' => Carbon::now()->subDays(9),
        'created_at' => Carbon::now()->subDays(9),
        'updated_at' => Carbon::now()->subDays(9),
    ],

    // -- Cafes --
    [
        'title' => 'The Little Red Fox Espresso',
        'province' => 'Siem Reap',
        'category' => 'Cafe',
        'content' => 'A stylish and socially-conscious cafe in Siem Reap, The Little Red Fox is famous for its exceptional coffee, creative cocktails, and delicious bites. With a strong focus on sustainability and supporting local artists, it offers a vibrant atmosphere in the heart of the Kandal Village arts district.',
        'image' => 'posts/little_red_fox.jpg',
        'published_at' => Carbon::now()->subDays(12),
        'created_at' => Carbon::now()->subDays(12),
        'updated_at' => Carbon::now()->subDays(12),
    ],
    [
        'title' => 'Cafe Espresso',
        'province' => 'Kampot',
        'category' => 'Cafe',
        'content' => 'Cafe Espresso is a popular cafe brand in Cambodia, and its Kampot location offers a relaxed space to enjoy expertly brewed coffee and fresh food. Sourcing high-quality beans, they provide a consistently good caffeine fix, making it a favorite spot for both locals and travelers exploring the riverside town.',
        'image' => 'posts/Cafe Espresso.jpg',
        'published_at' => Carbon::now()->subDays(12),
        'created_at' => Carbon::now()->subDays(12),
        'updated_at' => Carbon::now()->subDays(12),
    ],
    [
        'title' => 'Feel Good Cafe',
        'province' => 'Phnom Penh',
        'category' => 'Cafe',
        'content' => "A pioneer in Cambodia's specialty coffee scene, Feel Good Cafe is known for roasting its own blend of regional coffee beans. The cafe offers a welcoming, relaxed environment with a diverse menu of breakfast, lunch, and Mexican-inspired dishes, plus a dedicated kids' play area.",
        'image' => 'posts/feel_good_cafe.jpg',
        'published_at' => Carbon::now()->subDays(12),
        'created_at' => Carbon::now()->subDays(12),
        'updated_at' => Carbon::now()->subDays(12),
    ],

    // -- Temples --
    [
        'title' => 'Banteay Chhmar',
        'province' => 'Banteay Meanchey',
        'category' => 'Temple',
        'content' => "A massive, remote, and atmospheric temple complex built by Jayavarman VII. Famous for its stunning bas-reliefs, including the multi-armed Avalokiteshvara, it remains largely unrestored and engulfed by jungle, offering a truly authentic, off-the-beaten-path explorer experience.",
        'image' => 'posts/banteay_chhmar.jpg',
        'published_at' => Carbon::now()->subDays(15),
        'created_at' => Carbon::now()->subDays(15),
        'updated_at' => Carbon::now()->subDays(15),
    ], 
    [
        'title' => 'Prasat Bakan (Preah Khan of Kampong Svay)',
        'province' => 'Preah Vihear',
        'category' => 'Temple',
        'content' => "Considered the largest single temple complex ever built by the Khmer Empire, Prasat Bakan is a vast and remote site. Its sheer scale and isolation make it a destination for true adventurers. The complex includes the iconic face-towers similar to Bayon, surrounded by moats and ancient walls.",
        'image' => 'posts/prasat_bakan.webp',
        'published_at' => Carbon::now()->subDays(15),
        'created_at' => Carbon::now()->subDays(15),
        'updated_at' => Carbon::now()->subDays(15),
    ],

    // -- National Parks --
    [
        'title' => 'Botum Sakor National Park',
        'province' => 'Koh Kong',
        'category' => 'Nationalpark',
        'content' => "As Cambodia's largest national park, Botum Sakor encompasses a diverse range of ecosystems from dense evergreen rainforests to coastal mangroves. It's a critical habitat for endangered species like the Asian elephant and clouded leopard. Eco-lodges offer boat and hiking tours to explore its rich biodiversity.",
        'image' => 'posts/botum_sakor_park.jpg',
        'published_at' => Carbon::now()->subDays(18),
        'created_at' => Carbon::now()->subDays(18),
        'updated_at' => Carbon::now()->subDays(18),
    ], 
    [
        'title' => 'Virachey National Park',
        'province' => 'Ratanakiri',
        'category' => 'Nationalpark',
        'content' => "One of Southeast Asia's most remote and pristine wildernesses, Virachey is an ASEAN Heritage Park. It is a destination for serious multi-day treks, offering a true jungle adventure through dense forests, grasslands, and mountains, with chances to spot rare wildlife and experience local indigenous culture.",
        'image' => 'posts/virachey_national_park.png',
        'published_at' => Carbon::now()->subDays(18),
        'created_at' => Carbon::now()->subDays(18),
        'updated_at' => Carbon::now()->subDays(18),
    ],

    // -- Palaces --
    [
        'title' => 'The Throne Hall',
        'province' => 'Phnom Penh',
        'category' => 'Palace',
        'content' => "The main building of the Royal Palace complex, the Throne Hall (Preah Tineang Tevea Vinichhay) is a spectacular example of Khmer architecture. Used for coronations and official ceremonies, its magnificent, tiered roof and gilded decorations make it a stunning centerpiece that visitors can admire from the outside.",
        'image' => 'posts/throne_hall.jpg',
        'published_at' => Carbon::now()->subDays(21),
        'created_at' => Carbon::now()->subDays(21),
        'updated_at' => Carbon::now()->subDays(21),
    ],
    [
        'title' => 'The Silver Pagoda',
        'province' => 'Phnom Penh',
        'category' => 'Palace',
        'content' => "Located on the south side of the Royal Palace complex, the Silver Pagoda is famed for its floor, which is covered with five tons of gleaming silver. It houses many national treasures, including a life-sized gold Buddha encrusted with 9,584 diamonds and a 17th-century emerald Buddha.",
        'image' => 'posts/silver_pagoda.avif',
        'published_at' => Carbon::now()->subDays(21),
        'created_at' => Carbon::now()->subDays(21),
        'updated_at' => Carbon::now()->subDays(21),
    ],
    [
        'title' => 'Napoleon III Pavilion',
        'province' => 'Phnom Penh',
        'category' => 'Palace',
        'content' => "A unique structure within the Royal Palace grounds, this iron building was a gift from France's Emperor Napoleon III. Originally built for the opening of the Suez Canal in Egypt, it was given to King Norodom in 1876. Its European style stands in stark contrast to the surrounding traditional Khmer architecture.",
        'image' => 'posts/napoleon_pavilion.jpg',
        'published_at' => Carbon::now()->subDays(21),
        'created_at' => Carbon::now()->subDays(21),
        'updated_at' => Carbon::now()->subDays(21),
    ],

    // -- Monuments --
     
    [
        'title' => 'Cambodia-Vietnam Friendship Monument',
        'province' => 'Phnom Penh',
        'category' => 'Monument',
        'content' => "Built by the communist regime in 1979, this monument commemorates the alliance between Cambodia and Vietnam that led to the overthrow of the Khmer Rouge. Located in a park near the Royal Palace, it depicts soldiers from both nations and serves as a historical and political landmark.",
        'image' => 'posts/friendship_monument.jpg',
        'published_at' => Carbon::now()->subDays(24),
        'created_at' => Carbon::now()->subDays(24),
        'updated_at' => Carbon::now()->subDays(24),
    ],
    [
        'title' => 'Statue of King Father Norodom Sihanouk',
        'province' => 'Phnom Penh',
        'category' => 'Monument',
        'content' => "Erected in 2013, this impressive bronze statue honors the revered late King Father Norodom Sihanouk. Housed under a 27-meter-high stupa near the Independence Monument, it is a place where Cambodians come to pay their respects to the figure who led the country to independence and through much of its modern history.",
        'image' => 'posts/sihanouk_statue.jpg',
        'published_at' => Carbon::now()->subDays(24),
        'created_at' => Carbon::now()->subDays(24),
        'updated_at' => Carbon::now()->subDays(24),
    ],

    // -- Lakes --
    [
        'title' => 'Boeng Yeak Laom',
        'province' => 'Ratanakiri',
        'category' => 'Lake',
        'content' => "A stunningly beautiful volcanic crater lake with a near-perfect circular shape and crystal-clear emerald water. Located near Banlung, it's a sacred place for the local Tampuan people and a popular spot for swimming, picnicking, and hiking the trail that encircles the water.",
        'image' => 'posts/yeak_laom_lake.jpg',
        'published_at' => Carbon::now()->subDays(27),
        'created_at' => Carbon::now()->subDays(27),
        'updated_at' => Carbon::now()->subDays(27),
    ],
    [
        'title' => 'Tonle Bati',
        'province' => 'Takeo',
        'category' => 'Lake',
        'content' => "A popular lakeside weekend retreat for residents of Phnom Penh. The main attraction is the serene lake itself, where locals rent out bamboo huts over the water for picnics and relaxation. The area also features two ancient Angkorian temples, Ta Prohm and Yeay Peau, making it a great blend of leisure and history.",
        'image' => 'posts/tonle_bati_lake.jpg',
        'published_at' => Carbon::now()->subDays(27),
        'created_at' => Carbon::now()->subDays(27),
        'updated_at' => Carbon::now()->subDays(27),
    ],
    [
        'title' => 'Kamping Puoy Lake',
        'province' => 'Battambang',
        'category' => 'Lake',
        'content' => "A large reservoir with a tragic history, having been built by forced labor during the Khmer Rouge regime. Today, it is a popular spot for locals, especially on weekends. Visitors can relax in thatch huts, enjoy a boat ride, and admire the lotus flowers that bloom on the water's surface.",
        'image' => 'posts/kamping_puoy_lake.jpg',
        'published_at' => Carbon::now()->subDays(27),
        'created_at' => Carbon::now()->subDays(27),
        'updated_at' => Carbon::now()->subDays(27),
    ],

    // -- Rivers --
    [
        'title' => 'Teuk Chhou River',
        'province' => 'Kampot',
        'category' => 'River',
        'content' => "The scenic river that flows through the heart of Kampot town. It is the center of life and activity, famous for its relaxing sunset cruises where you can often see fireflies light up the riverside trees. Kayaking, paddleboarding, and swimming are popular activities from the many guesthouses that line its banks.",
        'image' => 'posts/teuk_chhou_river.jpg',
        'published_at' => Carbon::now()->subDays(30),
        'created_at' => Carbon::now()->subDays(30),
        'updated_at' => Carbon::now()->subDays(30),
    ],
    [
        'title' => 'Preaek Tuek Sap River',
        'province' => 'Kampot',
        'category' => 'River',
        'content' => "A beautiful river system just outside of Kampot, known as the 'Green Cathedral' for its lush, jungle-like mangrove canopy that arches over the water. It's a serene and stunning location for a boat trip or kayak adventure, offering a peaceful immersion into coastal nature.",
        'image' => 'posts/green_cathedral_river.jpg',
        'published_at' => Carbon::now()->subDays(30),
        'created_at' => Carbon::now()->subDays(30),
        'updated_at' => Carbon::now()->subDays(30),
    ],
    [
        'title' => 'Tatai River',
        'province' => 'Koh Kong',
        'category' => 'River',
        'content' => "Winding through the Cardamom Mountains, the Tatai River is a pristine waterway offering access to incredible nature and eco-tourism experiences. Home to the spectacular Tatai Waterfall, the river is best explored by boat from one of the several floating lodges or luxury tented camps along its banks.",
        'image' => 'posts/tatai_river.jpg',
        'published_at' => Carbon::now()->subDays(30),
        'created_at' => Carbon::now()->subDays(30),
        'updated_at' => Carbon::now()->subDays(30),
    ],

    // -- Hotels --
    [
        'title' => 'Shinta Mani Wild',
        'province' => 'Koh Kong',
        'category' => 'Hotel',
        'content' => "A radical concept in luxury camping, Shinta Mani Wild is set along a river in the Cardamom Mountains. Guests arrive by zip-line and stay in extravagant tents. The all-inclusive experience combines world-class design with conservation, offering unique excursions with Wildlife Alliance rangers.",
        'image' => 'posts/shinta_mani_wild.jpg',
        'published_at' => Carbon::now()->subDays(33),
        'created_at' => Carbon::now()->subDays(33),
        'updated_at' => Carbon::now()->subDays(33),
    ],
    [
        'title' => 'Banteay Srei',
        'province' => 'Siem Reap',
        'category' => 'Temple',
        'content' => 'A 10th-century Cambodian temple dedicated to the Hindu god Shiva. Located in the area of Angkor, it lies near the hill of Phnom Dei, 25 km (16 mi) north-east of the main group of temples that once belonged to the medieval capitals of Yasodharapura and Angkor Thom.',
        'image' => 'posts/banteay_srei.jpg',
        'published_at' => Carbon::now()->subDays(2),
        'created_at' => Carbon::now()->subDays(2),
        'updated_at' => Carbon::now()->subDays(2),
    ],
    [
        'title' => 'The Missing Sock Cafe',
        'province' => 'Siem Reap',
        'category' => 'Cafe',
        'content' => 'A cozy and quirky cafe in the heart of Siem Reap, known for its excellent coffee, delicious brunch options, and friendly atmosphere. A great place to relax after exploring the nearby temples.',
        'image' => 'posts/missing_sock_cafe.jpg',
        'published_at' => Carbon::now()->subDays(3),
        'created_at' => Carbon::now()->subDays(3),
        'updated_at' => Carbon::now()->subDays(3),
    ],
    [
        'title' => 'Phare, The Cambodian Circus',
        'province' => 'Siem Reap',
        'category' => 'Entertainment',
        'content' => 'More than just a circus, Phare performers use theater, music, dance and modern circus arts to tell uniquely Cambodian stories; historical, folk and modern. The young circus artists will astonish you with their energy, emotion, enthusiasm and talent.',
        'image' => 'posts/phare_circus.jpg',
        'published_at' => Carbon::now()->subDays(4),
        'created_at' => Carbon::now()->subDays(4),
        'updated_at' => Carbon::now()->subDays(4),
    ],
    [
        'title' => 'La Plantation',
        'province' => 'Kampot',
        'category' => 'Farm',
        'content' => 'A certified organic farm and a social enterprise, La Plantation is a must-visit in Kampot. It offers free guided tours where visitors can learn about the famous Kampot pepper, as well as other spices, and enjoy tastings.',
        'image' => 'posts/la_plantation.jpg',
        'published_at' => Carbon::now()->subDays(6),
        'created_at' => Carbon::now()->subDays(6),
        'updated_at' => Carbon::now()->subDays(6),
    ],
    [
        'title' => 'Kep National Park',
        'province' => 'Kep',
        'category' => 'Nationalpark',
        'content' => 'A beautiful national park with well-marked trails, offering stunning views of the coastline and surrounding islands. It\'s a great place for a hike or a leisurely walk, with opportunities to spot various wildlife.',
        'image' => 'posts/kep_national_park.jpg',
        'published_at' => Carbon::now()->subDays(7),
        'created_at' => Carbon::now()->subDays(7),
        'updated_at' => Carbon::now()->subDays(7),
    ],
    [
        'title' => 'Rabbit Island (Koh Tonsay)',
        'province' => 'Kep',
        'category' => 'Island',
        'content' => 'A short boat ride from Kep, Rabbit Island is a rustic paradise with beautiful sandy beaches and clear waters. It\'s a perfect spot for a day trip or an overnight stay in a simple bungalow.',
        'image' => 'posts/rabbit_island.jpg',
        'published_at' => Carbon::now()->subDays(8),
        'created_at' => Carbon::now()->subDays(8),
        'updated_at' => Carbon::now()->subDays(8),
    ],
    [
        'title' => 'Sokha Beach',
        'province' => 'Preah Sihanouk',
        'category' => 'Beach',
        'content' => 'One of the most beautiful and well-maintained beaches in Sihanoukville, Sokha Beach offers pristine white sand and calm, clear waters. While part of the beach is private for the Sokha Beach Resort, a section is open to the public.',
        'image' => 'posts/sokha_beach.jpg',
        'published_at' => Carbon::now()->subDays(9),
        'created_at' => Carbon::now()->subDays(9),
        'updated_at' => Carbon::now()->subDays(9),
    ],
    [
        'title' => 'Kbal Chhay Waterfall',
        'province' => 'Preah Sihanouk',
        'category' => 'Waterfall',
        'content' => 'Located about 16 kilometers from the center of Sihanoukville, Kbal Chhay Waterfall is a series of cascades that are most impressive during the rainy season. It\'s a popular spot for locals to have picnics and enjoy nature.',
        'image' => 'posts/kbal_chhay_waterfall.jpg',
        'published_at' => Carbon::now()->subDays(10),
        'created_at' => Carbon::now()->subDays(10),
        'updated_at' => Carbon::now()->subDays(10),
    ],
    [
        'title' => 'Bamboo Train',
        'province' => 'Battambang',
        'category' => 'Entertainment',
        'content' => 'A unique and thrilling experience, the Bamboo Train (Norry) is a simple bamboo platform powered by a small engine. It rides on the railway tracks and offers a fun way to see the Cambodian countryside.',
        'image' => 'posts/bamboo_train.jpg',
        'published_at' => Carbon::now()->subDays(11),
        'created_at' => Carbon::now()->subDays(11),
        'updated_at' => Carbon::now()->subDays(11),
    ],
    [
        'title' => 'Wat Ek Phnom',
        'province' => 'Battambang',
        'category' => 'Temple',
        'content' => 'An 11th-century Hindu temple with some well-preserved carvings. The temple ruins are located next to a modern pagoda, creating a striking contrast between the old and the new.',
        'image' => 'posts/Wat Ek Phnom.jpg',
        'published_at' => Carbon::now()->subDays(12),
        'created_at' => Carbon::now()->subDays(12),
        'updated_at' => Carbon::now()->subDays(12),
    ],
    [
        'title' => 'Virachey National Park',
        'province' => 'Ratanakiri',
        'category' => 'Nationalpark',
        'content' => 'One of the largest and most biodiverse national parks in Cambodia, Virachey is a remote and pristine wilderness area. It\'s a destination for serious trekkers and nature lovers, offering opportunities to spot rare wildlife.',
        'image' => 'posts/virachey_national_park.png',
        'published_at' => Carbon::now()->subDays(13),
        'created_at' => Carbon::now()->subDays(13),
        'updated_at' => Carbon::now()->subDays(13),
    ],
    [
        'title' => 'Yeak Laom Lake',
        'province' => 'Ratanakiri',
        'category' => 'Lake',
        'content' => 'A stunning volcanic crater lake with crystal-clear water, surrounded by lush forest. It\'s a sacred place for the local indigenous communities and a popular spot for swimming and hiking.',
        'image' => 'posts/yeak_laom_lake.jpg',
        'published_at' => Carbon::now()->subDays(14),
        'created_at' => Carbon::now()->subDays(14),
        'updated_at' => Carbon::now()->subDays(14),
    ],
    [
        'title' => 'Bousra Waterfall',
        'province' => 'Mondulkiri',
        'category' => 'Waterfall',
        'content' => 'One of the most impressive waterfalls in Cambodia, Bousra is a multi-tiered cascade with a powerful flow, especially during the rainy season. It\'s a popular attraction for both tourists and locals.',
        'image' => 'posts/bousra_waterfall.jpg',
        'published_at' => Carbon::now()->subDays(15),
        'created_at' => Carbon::now()->subDays(15),
        'updated_at' => Carbon::now()->subDays(15),
    ],
    [
        'title' => 'Elephant Valley Project',
        'province' => 'Mondulkiri',
        'category' => 'Sanctuary',
        'content' => 'An ethical elephant sanctuary where visitors can observe elephants in their natural habitat. The project focuses on elephant welfare and conservation, offering a unique and responsible way to interact with these gentle giants.',
        'image' => 'posts/elephant_valley_project.jpg',
        'published_at' => Carbon::now()->subDays(16),
        'created_at' => Carbon::now()->subDays(16),
        'updated_at' => Carbon::now()->subDays(16),
    ] 
        ];

        $finalPosts = [];
        $existingSlugs = [];
        foreach ($posts as $post) {
            $categoryKey = strtolower($post['category']);
            $provinceKey = strtolower($post['province']);
            $categoryId = $categoryMap[$categoryKey] ?? null;
            $provinceId = $provinceMap[$provinceKey] ?? null;
            if ($categoryId && $provinceId) {
                $slug = Str::slug($post['title']);
                // Check if this slug already exists in the database
                $existsInDb = DB::table('posts')->where('slug', $slug)->exists();
                if ($existsInDb || in_array($slug, $existingSlugs)) {
                    // Duplicate found in DB or in this batch, skip this post
                    continue;
                }
                $existingSlugs[] = $slug;
                $finalPosts[] = [
                    'title' => $post['title'],
                    'slug' => $slug,
                    'province_id' => $provinceId,
                    'category_id' => $categoryId,
                    'content' => $post['content'],
                    'image' => $post['image'],
                    'published_at' => $post['published_at'],
                    'created_at' => $post['created_at'],
                    'updated_at' => $post['updated_at'],
                ];
            }
        }

        DB::table('posts')->insert($finalPosts);
    }
}
